<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class contentmodelsTaxonomyProxy extends \content\models\Taxonomy implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function id()
    {
        $this->__load();
        return parent::id();
    }

    public function getTerm()
    {
        $this->__load();
        return parent::getTerm();
    }

    public function setTerm(\content\models\Term $term)
    {
        $this->__load();
        return parent::setTerm($term);
    }

    public function setTaxonomy($taxonomy)
    {
        $this->__load();
        return parent::setTaxonomy($taxonomy);
    }

    public function getTaxonomy()
    {
        $this->__load();
        return parent::getTaxonomy();
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent(\content\models\Taxonomy $parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function addChild(\content\models\Taxonomy $child)
    {
        $this->__load();
        return parent::addChild($child);
    }

    public function removeChild(\content\models\Taxonomy $child)
    {
        $this->__load();
        return parent::removeChild($child);
    }

    public function getContents()
    {
        $this->__load();
        return parent::getContents();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'term', 'taxonomy', 'parent', 'children', 'contents');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}